# SwiftLint:
# https://github.com/realm/SwiftLint
#
# Built-in Rules:
# https://github.com/realm/SwiftLint/blob/master/Rules.md

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Vendor
  - StudyPathTrakerTests

opt_in_rules: # some rules are only opt-in
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - discouraged_object_literal
  - override_in_extension

type_body_length:
  - 450 # warning
  - 500 # error

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - url

force_unwrapping:
  severity: error


custom_rules:
  self_shadow:
    name: "Self Shadow"
    regex: '`self`'
    match_kinds:
      - identifier
    message: "Use of ``self`` is technically a bug in the Swift compiler. Use `strongSelf` instead."
    severity: error

  screen_bounds:
    name: "Screen Bounds"
    regex: 'UIScreen\s*\.\s*main\s*\.\s*bounds'
    match_kinds:
      - identifier
    message: "NEVER use a screen's bounds for anything. Please refactor this!"
    severity: warning

  status_bar_orientation:
    name: "Status Bar Orientation"
    regex: 'statusBarOrientation'
    match_kinds:
      - identifier
    message: "NEVER use the status bar's orientation for anything. Please refactor this!"
    severity: error

  comment_spacing:
    name: "Comment Spacing"
    regex: '(\/\/[^\s\/*]|[^\s\/*]\/\/)'
    match_kinds:
      - comment
      - doccomment
    message: "Single-line comments should have at least one whitespace character before and after the '//' or '///'."
    severity: warning

  fatal_error:
    name: "Use of `fatalError`"
    regex: 'fatalError'
    message: "Prefer using 'assertionFailure' and failing gracefully instead of `fatalError`. `assertionFailure` will not cause a crash in production builds, but `fatalError` will. If you absolutely must use `fatalError`, silence this warning by adding `// swiftlint:disable:next fatal_error` above this line."
    match_kinds:
      - identifier
    severity: warning

  common_init:
    name: "Definition of `commonInit` Method"
    regex: 'func\s+commonInit\s*\('
    message: "Please don't name methods `commonInit` as it may be possible for subclasses to inadvertently override them without you knowing it. Instead, consider naming it something like `commonInitClassName`."
    severity: error

  explicit_comparison_to_true:
    name: "Explicit comparison to `true`"
    regex: '(==\s*true|true\s*==|!=\s*true|true\s*!=)'
    message: "Please don't explicitly compare to `true`. If you need to compare an optional `Bool`, provide a default value instead, like `?? true` or `?? false`."
    severity: warning
disabled_rules: # rule identifiers to exclude from running
 - line_length
 - trailing_whitespace
